"""
tests/test_ingestion.py — Unit tests for ingestion/base_source, file_source, registry.

All tests are hermetic: no network calls, no real database.
Fixture files are generated by conftest.py if absent.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import pandas as pd
import pytest

from ingestion.file_source import FileSource

# Expected columns produced by make_fixtures.build_fixtures()
EXPECTED_COLUMNS = {
    "patient_id", "age", "state", "diagnosis", "visit_date", "cost_usd"
}
EXPECTED_ROW_COUNT = 20


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _source() -> FileSource:
    """Return a fresh FileSource instance for each test."""
    return FileSource()


# ---------------------------------------------------------------------------
# CSV
# ---------------------------------------------------------------------------

class TestCSVLoading:
    """Tests for CSV file loading via FileSource."""

    def test_csv_row_count(self, fixture_csv: Path) -> None:
        """CSV fixture must load exactly 20 rows."""
        df = _source().extract(filepath=str(fixture_csv))
        assert len(df) == EXPECTED_ROW_COUNT

    def test_csv_columns(self, fixture_csv: Path) -> None:
        """CSV fixture must have the expected column set."""
        df = _source().extract(filepath=str(fixture_csv))
        assert EXPECTED_COLUMNS == set(df.columns)

    def test_csv_chunk_size(self, fixture_csv: Path) -> None:
        """Chunked CSV read must produce the same 20 rows as a direct read."""
        df = _source().extract(filepath=str(fixture_csv), chunk_size=7)
        assert len(df) == EXPECTED_ROW_COUNT
        assert EXPECTED_COLUMNS == set(df.columns)

    def test_csv_encoding_fallback_latin1(self) -> None:
        """A latin-1 file containing é must load successfully via fallback chain."""
        content = "name,note\nJosé,café\nAna,résumé\n"
        with tempfile.NamedTemporaryFile(
            suffix=".csv", mode="wb", delete=False
        ) as tmp:
            tmp.write(content.encode("latin-1"))
            tmp_path = Path(tmp.name)

        try:
            df = _source().extract(filepath=str(tmp_path))
            assert len(df) == 2
            assert "José" in df["name"].values
        finally:
            tmp_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------

class TestJSONLoading:
    """Tests for JSON file loading via FileSource."""

    def test_json_row_count(self, fixture_json: Path) -> None:
        """JSON fixture must load exactly 20 rows."""
        df = _source().extract(filepath=str(fixture_json))
        assert len(df) == EXPECTED_ROW_COUNT

    def test_json_columns(self, fixture_json: Path) -> None:
        """JSON fixture must have the expected column set."""
        df = _source().extract(filepath=str(fixture_json))
        assert EXPECTED_COLUMNS == set(df.columns)


# ---------------------------------------------------------------------------
# Parquet
# ---------------------------------------------------------------------------

class TestParquetLoading:
    """Tests for Parquet file loading via FileSource."""

    def test_parquet_row_count(self, fixture_parquet: Path) -> None:
        """Parquet fixture must load exactly 20 rows."""
        df = _source().extract(filepath=str(fixture_parquet))
        assert len(df) == EXPECTED_ROW_COUNT

    def test_parquet_columns(self, fixture_parquet: Path) -> None:
        """Parquet fixture must have the expected column set."""
        df = _source().extract(filepath=str(fixture_parquet))
        assert EXPECTED_COLUMNS == set(df.columns)

    def test_parquet_values_intact(self, fixture_parquet: Path) -> None:
        """Spot-check a value to confirm pyarrow round-trip is lossless."""
        df = _source().extract(filepath=str(fixture_parquet))
        # Row 0: patient P001, age 34 — asserts on values not dtype
        row = df[df["patient_id"] == "P001"].iloc[0]
        assert int(row["age"]) == 34


# ---------------------------------------------------------------------------
# XLSX
# ---------------------------------------------------------------------------

class TestXLSXLoading:
    """Tests for Excel file loading via FileSource."""

    def test_xlsx_row_count(self, fixture_xlsx: Path) -> None:
        """XLSX fixture must load exactly 20 rows."""
        df = _source().extract(filepath=str(fixture_xlsx))
        assert len(df) == EXPECTED_ROW_COUNT

    def test_xlsx_columns(self, fixture_xlsx: Path) -> None:
        """XLSX fixture must have the expected column set."""
        df = _source().extract(filepath=str(fixture_xlsx))
        assert EXPECTED_COLUMNS == set(df.columns)


# ---------------------------------------------------------------------------
# Error / edge-case handling
# ---------------------------------------------------------------------------

class TestErrorHandling:
    """FileSource must never raise; bad inputs return empty DataFrames."""

    def test_missing_file_returns_empty_dataframe(self) -> None:
        """Non-existent file path must return an empty DataFrame, not raise."""
        df = _source().extract(filepath="/no/such/file/nowhere.csv")
        assert isinstance(df, pd.DataFrame)
        assert df.empty

    def test_unsupported_suffix_returns_empty_dataframe(
        self, sample_dir: Path
    ) -> None:
        """A file with an unsupported suffix (.xyz) must return empty DataFrame."""
        bad_path = sample_dir / "fake.xyz"
        bad_path.write_text("hello")
        try:
            df = _source().extract(filepath=str(bad_path))
            assert isinstance(df, pd.DataFrame)
            assert df.empty
        finally:
            bad_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Metadata bookkeeping
# ---------------------------------------------------------------------------

class TestMetadataBookkeeping:
    """last_extract_time and last_record_count must be updated after extract."""

    def test_record_count_updated_after_extract(self, fixture_csv: Path) -> None:
        """last_record_count must equal row count after a successful extract."""
        src = _source()
        assert src.last_record_count == -1  # initial sentinel
        src.extract(filepath=str(fixture_csv))
        assert src.last_record_count == EXPECTED_ROW_COUNT

    def test_extract_time_set_after_extract(self, fixture_csv: Path) -> None:
        """last_extract_time must be populated after a successful extract."""
        src = _source()
        assert src.last_extract_time is None
        src.extract(filepath=str(fixture_csv))
        assert src.last_extract_time is not None

    def test_get_metadata_keys(self, fixture_csv: Path) -> None:
        """get_metadata() must return all required keys."""
        src = _source()
        src.extract(filepath=str(fixture_csv))
        meta = src.get_metadata()
        required = {
            "name", "description", "source_type",
            "last_extract_time", "last_record_count",
        }
        assert required.issubset(meta.keys())
        assert meta["source_type"] == "file"
        assert meta["last_record_count"] == EXPECTED_ROW_COUNT


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

class TestRegistry:
    """SourceRegistry must auto-register FileSource and handle lookups."""

    def test_file_source_registered(self) -> None:
        """SourceRegistry must contain a 'file' entry by default."""
        from ingestion.registry import SourceRegistry
        registry = SourceRegistry()
        source = registry.get("file")
        assert source is not None
        assert source.name == "file"

    def test_get_unknown_returns_none(self) -> None:
        """get() on an unknown name must return None."""
        from ingestion.registry import SourceRegistry
        registry = SourceRegistry()
        assert registry.get("nope") is None

    def test_list_sources_non_empty(self) -> None:
        """list_sources() must return at least one entry."""
        from ingestion.registry import SourceRegistry
        registry = SourceRegistry()
        sources = registry.list_sources()
        assert isinstance(sources, list)
        assert len(sources) >= 1

    def test_list_sources_contains_file(self) -> None:
        """list_sources() must include the 'file' source metadata."""
        from ingestion.registry import SourceRegistry
        registry = SourceRegistry()
        names = [s["name"] for s in registry.list_sources()]
        assert "file" in names

    def test_check_all_connections_file_true(self) -> None:
        """check_all_connections() must report file source as True."""
        from ingestion.registry import SourceRegistry
        registry = SourceRegistry()
        results = registry.check_all_connections()
        assert results.get("file") is True

    def test_register_custom_source(self) -> None:
        """A manually registered source must be retrievable by name."""
        from ingestion.registry import SourceRegistry
        from ingestion.base_source import BaseSource

        class _DummySource(BaseSource):
            source_type = "api"

            def connect(self) -> bool:
                return True

            def extract(self, **kwargs) -> pd.DataFrame:
                return pd.DataFrame()

        registry = SourceRegistry(auto_register=False)
        dummy = _DummySource(name="dummy", description="Test only")
        registry.register(dummy)
        assert registry.get("dummy") is dummy

    def test_empty_registry_list(self) -> None:
        """An empty registry (auto_register=False) must return an empty list."""
        from ingestion.registry import SourceRegistry
        registry = SourceRegistry(auto_register=False)
        assert registry.list_sources() == []
